name: persona_flutter
description: Persona Inquiry for Flutter. Integrates the native v1 SDKs for iOS and Android .
version: 2.1.3
homepage: https://github.com/jorgefspereira/persona_flutter
repository: https://github.com/jorgefspereira/persona_flutter
issue_tracker: https://github.com/jorgefspereira/persona_flutter/issues
screenshots:
  - description: The persona logo.
    path: screenshots/logo.png

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jorgefspereira.persona_flutter
        pluginClass: PersonaFlutterPlugin
      ios:
        pluginClass: PersonaFlutterPlugin
